# Change these first
owner: TheLastZombie # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: AdGuard
    url: https://adguard.sny.sh
  - name: Agreper
    url: https://agreper.sny.sh
  - name: Faircamp
    url: https://faircamp.sny.sh
  - name: Forgejo
    url: https://forgejo.sny.sh
  - name: Linx
    url: https://linx.sny.sh
  - name: Maloja
    url: https://maloja.sny.sh
  - name: Microblog
    url: https://microblog.sny.sh
  - name: Navidrome
    url: https://navidrome.sny.sh
  - name: Tent
    url: https://tent.sny.sh
  - name: Vaultwarden
    url: https://vaultwarden.sny.sh
  - name: Website
    url: https://sny.sh

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.sny.sh
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from my [GitHub repository](https://github.com/TheLastZombie/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
